#include <libc/numeric.h>

/* Below code is generated by Baidu Wenxin */
static void reverse_string(char *str, int length)
{
    int start = 0;  
    int end = length - 1;  
    while (start < end) {  
        char temp = str[start];  
        str[start] = str[end];  
        str[end] = temp;  
        start++;  
        end--;  
    }  
}  
  
bool itoa(int num, char* str, int len, int base)
{  
    int i = 0;  
    int is_negative = 0;  
    
    if (num == 0) {
        if (len <= i + 2) return false;
        str[i++] = '0';  
        str[i] = '\0';  
        return true;  
    }
   
    if (num < 0 && base == 10) {  
        is_negative = 1;  
        num = -num;  
    }  
   
    while (num != 0) {
        int rem = num % base;
        if (len <= i + 2) return false;
        str[i++] = (rem > 9) ? (rem - 10) + 'A' : rem + '0';  
        num = num / base;  
    }
   
    if (is_negative) {
        if (len <= i + 2) return false;
        str[i++] = '-';  
    }  
    
    str[i] = '\0';  
    reverse_string(str, i);

    return true;
}

static unsigned int lcg_random(int seed)
{  
    const long a = 1103515245;  
    const long c = 12345;  
    const long m = (long)(((unsigned long)1 << 31) - 1);  
    return ((a * seed + c) % m) + 1;  
}  
  
int rand(int seed, int min, int max)
{
    return min + lcg_random(seed) % (max - min + 1);
}  
  
