timeout: 3
editor_enabled: yes
graphics: yes
interface_resolution: 800x600

/HanOS
    protocol: limine
    path: boot():/hanos.elf
    module_path: boot():/initrd.tar
    module_cmdline: INITRD
    kaslr: no
    resolution: 800x600
