%ifndef CPU_MACROS_MAC
%define CPU_MACROS_MAC

    %macro push_all 0
        cld
        push r15
        push r14
        push r13
        push r12
        push r11
        push r10
        push r9
        push r8
        push rbp
        push rdi
        push rsi
        push rdx
        push rcx
        push rbx
        push rax
    %endmacro
    
    %macro pop_all 0
        pop rax
        pop rbx
        pop rcx
        pop rdx
        pop rsi
        pop rdi
        pop rbp
        pop r8
        pop r9
        pop r10
        pop r11
        pop r12
        pop r13
        pop r14
        pop r15
    %endmacro
    
    %macro pop_all_syscall 0
        add rsp, 8           ; skip saved rax (preserve handler's return value)
        pop rbx
        pop rcx
        pop rdx
        pop rsi
        pop rdi
        pop rbp
        pop r8
        pop r9
        pop r10
        pop r11
        pop r12
        pop r13
        pop r14
    %endmacro

%endif
