/**-----------------------------------------------------------------------------

 @file    numeric.c
 @brief   Implementation of numeric utility functions
 @details
 @verbatim

  This file contains the implementation of utility functions for numeric
  operations in the HanOS standard library. It includes the implementation of
  the function to convert an integer to a string representation (itoa), a
  helper function to reverse a string, and a function to generate a random
  integer within a specified range based on a seed value using a linear
  congruential generator (rand).

 @endverbatim

 **-----------------------------------------------------------------------------
 */
#include <stdint.h>
#include <numeric.h>

/* Below code is generated by Baidu Wenxin */
static void reverse_string(char *str, int32_t length)
{
    int32_t start = 0;
    int32_t end = length - 1;
    while (start < end) {
        char temp = str[start];
        str[start] = str[end];
        str[end] = temp;
        start++;
        end--;
    }
}

bool itoa(int32_t num, char *str, int32_t len, int32_t base)
{
    int32_t i = 0;
    int32_t is_negative = 0;

    if (num == 0) {
        if (len <= i + 2)
            return false;
        str[i++] = '0';
        str[i] = '\0';
        return true;
    }

    if (num < 0 && base == 10) {
        is_negative = 1;
        num = -num;
    }

    while (num != 0) {
        int32_t rem = num % base;
        if (len <= i + 2)
            return false;
        str[i++] = (rem > 9) ? (rem - 10) + 'A' : rem + '0';
        num = num / base;
    }

    if (is_negative) {
        if (len <= i + 2)
            return false;
        str[i++] = '-';
    }

    str[i] = '\0';
    reverse_string(str, i);

    return true;
}

static uint32_t lcg_random(int32_t seed)
{
    const int64_t a = 1103515245;
    const int64_t c = 12345;
    const int64_t m = (int64_t) (((uint64_t) 1 << 31) - 1);
    return ((a * seed + c) % m) + 1;
}

int32_t rand(int32_t seed, int32_t min, int32_t max)
{
    return min + lcg_random(seed) % (max - min + 1);
}
