/**-----------------------------------------------------------------------------

 @file    numeric.c
 @brief   Implementation of numeric utility functions
 @details
 @verbatim

  This file contains the implementation of utility functions for numeric
  operations in the HanOS standard library. It includes a function to generate
  a random integer within a specified range based on a seed value using a
  linear congruential generator (rand).

 @endverbatim

 **-----------------------------------------------------------------------------
 */
#include <stdint.h>
#include <numeric.h>

/* Below code is generated by Baidu Wenxin */
static uint32_t lcg_random(int32_t seed)
{
    const int64_t a = 1103515245;
    const int64_t c = 12345;
    const int64_t m = (int64_t) (((uint64_t) 1 << 31) - 1);
    return ((a * seed + c) % m) + 1;
}

int32_t rand(int32_t seed, int32_t min, int32_t max)
{
    return min + lcg_random(seed) % (max - min + 1);
}
