/**-----------------------------------------------------------------------------

 @file    help.h
 @brief   Definition of help command related data structures
 @details
 @verbatim

  The help list will be generated by genhelp from sourcec codes.

 @endverbatim

 **-----------------------------------------------------------------------------
 */
#pragma once

#include <stdint.h>
#include <libc/sysfunc.h>

extern const command_help_t _shell_helptab[];
